### ISSUE TITLE
How the code extract the pairings

### ISSUE THREAD

**Issue by arademaker** [ignaziomirto2017/nlpytaly#1]
I read the paper and I am curious to understand how this pairings are obtained and how they are represented. Can you point me to the right part of the code?

**Comment by ignaziomirto2017** [comment]
The part of the code which includes the pairings will be published with the next release, probably at the end of August 2021.
A web demo of the tool is already available. I will get in touch with you in case you want to have a try.

**Comment by arademaker** [comment]
Thank you
